version: "3.8"
services:
  db-service:
    image: mysql:lts
    container_name: db-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      - "${DB_PORT:-3306}:3306"
    cap_add:
      - SYS_NICE
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - --no-cache
    container_name: sync-student-container
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db-service
      - rabbitmq-service
      - mailpit-service
    volumes:
      - ./dist:/usr/src/app/dist


  phpmyadmin-service:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin-container
    restart: always
    environment:
      PMA_HOST: db-service
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_ARBITRARY: 1
    ports:
      - "8385:80"
    networks:
      - app-network

  rabbitmq-service:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-container
    restart: always
    ports:
      - '${RABBIT_PORT:-5673}:5672'
      - '${RABBIT_MANAGEMENT_PORT:-15673}:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBIT_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBIT_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBIT_VHOST}
    volumes:
      - rabbitmq-data-volume:/var/lib/rabbitmq
      - rabbitmq-log-volume:/var/log/rabbitmq
    networks:
      - app-network

  mailpit-service:
    image: axllent/mailpit
    container_name: mailpit-container
    restart: always
    volumes:
      - mailpit-data:/data
    ports:
      - '${EMAIL_WEB_PORT:-8025}:8025'
      - '${EMAIL_PORT:-1025}:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_UI_AUTH_USER: ${EMAIL_USER}
      MP_UI_AUTH_PASS: ${EMAIL_PASS}
      MP_SMTP_AUTH: ${EMAIL_USER}:${EMAIL_PASS}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  rabbitmq-data-volume:
    driver: local
  rabbitmq-log-volume:
    driver: local
  mailpit-data:
    driver: local